extern "C" {
void _ZN4aidl7android8hardware8security7keymint30BnRemotelyProvisionedComponent19getInterfaceVersionEPi() {}
void _ZN4aidl7android8hardware8security7keymint30BnRemotelyProvisionedComponent12createBinderEv() {}
void _ZN4aidl7android8hardware8security7keymint29IRemotelyProvisionedComponent10descriptorE() {}
void _ZN4aidl7android8hardware8security7keymint30BnRemotelyProvisionedComponentC2Ev() {}
void _ZN4aidl7android8hardware8security7keymint30BnRemotelyProvisionedComponentD2Ev() {}
void _ZN4aidl7android8hardware8security7keymint29IRemotelyProvisionedComponent4hashE() {}
void _ZN4aidl7android8hardware8security7keymint30BnRemotelyProvisionedComponent16getInterfaceHashEPNSt3__112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEE() {}
}